### ISSUE TITLE
Upload via form in rails 4.2

### ISSUE THREAD

**Issue by dg-ratiodata** [elabs/refile#120] opened 2015-01-17 21:10 UTC
I'm using the following software

```bash
[git:master]% bundle show refile
/home/user/.gem/ruby/2.2.0/gems/refile-0.5.0
[git:master]% bundle show rails
/home/user/.gem/ruby/2.2.0/gems/rails-4.2.0
```

This is my model

```ruby
class ValidationJob < ActiveRecord::Base
[...]
  attachment :source_file
[...]
end
```

I'm uploading the file using the form below

```haml
= form_for(@validation_job, html: { class: 'fe-form' }) do |f|
  - if @validation_job.errors.any?
    = render partial:'errors/saved_object', object: @validation_job

  .fe-form-field
    = f.attachment_field :source_file, class: 'fe-form-file-field'
  .fe-form-field
    = f.submit t('views.validation_jobs.new.link'), class: 'fe-button-new'
```

The params hash contains this:

```pry
[21] pry(#<ValidationJobsController>)> params['validation_job']['source_file']
=> #<ActionDispatch::Http::UploadedFile:0x000000041f8a98
@content_type="application/zip",
@headers="Content-Disposition: form-data; name=\"validation_job[source_file]\"; filename=\"blub.zip\"\r\nContent-Type: application/zip\r\n",
@original_filename="blub.zip",
@tempfile=#<File:/tmp/RackMultipart20150117-25550-28gxif.zip>>
```

When adding this to source_file
```pry
@validation_job.source_file = params['validation_job']['source_file']
```

This is the attachment after adding the file from from.

```pry
[29] pry(#<ValidationJobsController>)> @validation_job.source_file = params['validation_job']['source_file']
=> #<ActionDispatch::Http::UploadedFile:0x000000041f8a98
@content_type="application/zip",
@headers="Content-Disposition: form-data; name=\"validation_job[source_file]\"; filename=\"blub.zip\"\r\nContent-Type: application/zip\r\n",
@original_filename="blub.zip",
@tempfile=#<File:/tmp/RackMultipart20150117-25550-28gxif.zip>>
```

Now I'm gonna save the file.

```pry
[30] pry(#<ValidationJobsController>)> @validation_job.save!
(0.3ms)  BEGIN
SQL (0.3ms)  UPDATE "validation_jobs" SET "progress" = $1, "source_file_id" = $2, "updated_at" = $3 WHERE "validation_jobs"."id" = $4  [["progress", nil], ["source_file_id", "9456bb331274aca0e0ee66564e918aa18a47034404978ca142a3a2abb2ae"], ["updated_at", "2015-01-17 21:06:32.903457"], ["id", 9]]
(3.3ms)  COMMIT
=> true
```

What is weird, the size is zero.

```pry
[25] pry(#<ValidationJobsController>)> @validation_job.source_file.size
=> 0
```

But if I use `#tempfile` on `params`, then adding the file works differently.

```pry
[26] pry(#<ValidationJobsController>)> @validation_job.source_file = params['validation_job']['source_file'].tempfile
=> #<File:/tmp/RackMultipart20150117-25550-28gxif.zip>
```

Now it shows the correct size.

```pry
[27] pry(#<ValidationJobsController>)> @validation_job.source_file.size
=> 5754238
```

Anything I do/did wrong? Thanks a lot.

**Comment by jnicklas** [comment] 2015-01-18 00:17
First thing, try upgrading to 0.5.2.

I'm not quite sure what's going wrong here.

**Comment by dg-ratiodata** [comment] 2015-01-18 16:28
Done. Not fixed by upgrade.

```pry
[1] pry(#<ValidationJobsController>)> params['validation_job']['source_file']
=> #<ActionDispatch::Http::UploadedFile:0x007f7f4b35e158
@content_type="application/zip",
@headers="Content-Disposition: form-data; name=\"validation_job[source_file]\"; filename=\"blub.zip\"\r\nContent-Type: application/zip\r\n",
@original_filename="blub.zip",
@tempfile=#<File:/tmp/RackMultipart20150118-32543-u5efdy.zip>>

[2] pry(#<ValidationJobsController>)> @validation_job.source_file = params['validation_job']['source_file']
=> #<ActionDispatch::Http::UploadedFile:0x007f7f4b35e158
@content_type="application/zip",
@headers="Content-Disposition: form-data; name=\"validation_job[source_file]\"; filename=\"blub.zip\"\r\nContent-Type: application/zip\r\n",
@original_filename="blub.zip",
@tempfile=#<File:/tmp/RackMultipart20150118-32543-u5efdy.zip>>

[3] pry(#<ValidationJobsController>)> @validation_job.source_file.size
=> 0
```

```bash
[git:master]% bundle show refile
/home/user/.gem/ruby/2.2.0/gems/refile-0.5.3
```

**Comment by jnicklas** [comment] 2015-01-21 13:17
This is very strange. I have no idea how to help you though. This behaviour is quite well tested, and I can't replicated it locally. The very best would be if you were able to write a failing test case for this (see `spec/refile/feature`). Or failing that, provide an example application which shows off this failure. Try digging a bit deeper, into what the `size` method is doing and where it's going wrong. In pry, doing something like `show-source @validation_job.source_file.size` is a good starting point.

**Comment by dg-ratiodata** [comment] 2015-01-22 06:53
Ok. This is a "copied" rails application. I already remove `tmp/`. Is there any other directory which needs to be removed?

**Comment by jnicklas** [comment] 2015-01-22 13:59
Err link?

**Comment by jnicklas** [comment] 2015-01-27 19:19
I still can't understand what the problem is, unless you can specify it in more detail, I'll have to close this issue.

**Comment by dg-ratiodata** [comment] 2015-01-28 08:06
Ok. I will release the application as open source soon.

**Comment by jnicklas** [comment] 2015-01-28 09:02
Closing this for now, please let me know when you have more information.

**Closed by jnicklas** 2015-01-28 09:02 UTC

**Comment by dg-ratiodata** [comment] 2015-01-28 09:55
ok.

**Comment by maxmeyer** [comment] 2015-02-19 09:37
here's the application https://github.com/fedux-org/middleman-presentation-validator
